### ISSUE TITLE
Bug: Statistics when current month is january

### ISSUE THREAD

**Issue by u2032** [ioO/django-billjobs#40] opened 2019-01-09 12:24 UTC
In January, the page for statistics throws error 500.

The problem seems to be here, when computing the numero of current_month / current_year :
https://github.com/ioO/django-billjobs/blob/e7e901164a21a60d37179681a20e4a5764e3ddf4/billjobs/views.py#L299

The current computation is too simple and do not care about new year value.

Suggested change:
previous_month should be set to 12 if current_month = 1 but the uses of this field must be checked to be sure that it is used correctly according to current_year / previous_year also

**Comment by ioO** [comment] 2019-01-14 21:11
Duplicate of #39

**Closed by ioO** 2019-01-14 21:11 UTC
